# Generated by Django 4.2.11 on 2024-05-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
