# Generated by Django 4.2.11 on 2024-05-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_spartanews'),
        ('accounts', '0002_user_created_at'),
    ]

    operations = [
    ]
