# Generated by Django 4.2.11 on 2024-05-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_spartanews_0002_user_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spartanews',
        ),
    ]
