# Generated by Django 4.2.11 on 2024-05-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='spartanews',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
