# Generated by Django 4.2.11 on 2024-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_spartanews_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
