# Generated by Django 4.2.11 on 2024-05-10 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_comment_liked_by_spartanews_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spartanews',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
