# Generated by Django 4.2.11 on 2024-05-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_saved_by_spartanews_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='spartanews',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='spartanews',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
